### ISSUE TITLE
Binary name

### ISSUE THREAD

**Issue by devrimgunduz** [credativ/pg_checksums#10]
Hi,

Any particular reason why you are using the same name with the binary that comes with PostgreSQL?

It will cause confusion.

Regards, Devrim

**Comment by MichaelDBA** [comment]
Yeah, and it will all depend on which one is in the PATH first.   Since my issue dealt with different binaries for different PG versions which required a different name, this is not an issue with me since I append the name with "v_pg_version, ie, pg_checksums_v11.

**Comment by mbanck** [comment]
> Any particular reason why you are using the same name with the binary that comes with PostgreSQL?

1. this project was called `pg_checksums` before PostgreSQL had a tool of the same name.
2. it's essentially the same code anyway, with a few additions - I sync the code all the time.
3. The user-interface is identical as well (I think this `pg_checksums` might accept some additional legacy comand-line switches that were renamed upstream, but all the ones from the Postgres version are present).
 
> It will cause confusion.

What kind of confusion do you think it will cause?

**Comment by devrimgunduz** [comment]
Hi Michael,

I think this tool is useless without PostgreSQL, so there is an issue where two binaries with the same name will conflict.

I tried to build RPMs, and by default this software tries to install a binary called pg_checksums, which *tries to* overwrite the existing binary -- so it does not install.

I intended to use /usr/bin/pg_checksums, and then how about multiple version installations?

I also even thought about /usr/pg_checksums/11/bin/pg_checksums , but then I gave up. It was stupid.

You are free to keep the current name, but then I won't be able to RPMify it. Up to you.

Regards, Devrim

**Comment by mbanck** [comment]
About multiple version installations - see #9 - I believe `pg_checksums` should be built for each major version and I will add better checks/error reporting and update the documentation about this soon.

About RPM packaging - the Debian packaging ships a `/usr/lib/postgresql/<version>/bin/pg_checksums` (along all the other version-specific Postgres tools) for each Postgres major version. I am not sure whether we have any other external project that installs to that location, though. For the v12 issue, Debian uses the divert mechanism so if you install the v12 `pg_checksums` the upstream PG12 `pg_checksums` gets renamed on package installation and named back on removal, not sure whether RPM has a similar mechanism. The other sensible option would be to just not build `pg_checksums` for v12. Where do you install the upstream PG12 `pg_checksums`?

**Comment by mbanck** [comment]
Also, do you have any suggestions for a different name in case we do decide to rename at least the installed binary?

**Comment by MichaelDBA** [comment]
pg_filechecksums

**Comment by devrimgunduz** [comment]
> pg_filechecksums

That works :)

**Comment by devrimgunduz** [comment]
> About multiple version installations - see #9 - I believe `pg_checksums` should be built for each major version and I will add better checks/error reporting and update the documentation about this soon.
> 
> About RPM packaging - the Debian packaging ships a `/usr/lib/postgresql/<version>/bin/pg_checksums` (along all the other version-specific Postgres tools) for each Postgres major version. I am not sure whether we have any other external project that installs to that location, though. For the v12 issue, Debian uses the divert mechanism so if you install the v12 `pg_checksums` the upstream PG12 `pg_checksums` gets renamed on package installation and named back on removal, not sure whether RPM has a similar mechanism. The other sensible option would be to just not build `pg_checksums` for v12. Where do you install the upstream PG12 `pg_checksums`?

This is *doable*, but I will not replace a binary that comes with PostgreSQL.

**Comment by mbanck** [comment]
> pg_filechecksums

This makes it sound like `pg_filechecksums` was doing something pretty different to `pg_checksums`, so -1 from me. 

I could go with something `pg_checksums_next` (similar to `amcheck_next`), except I'm not sure whether the current changes will be in the next Postgres version (they either are not applicable (backbranch support) or got rejected at least as-is (online checksumming, `SIGUSR1` trigger).

Something like `pg_checksums_ng` or `pg_checksums++` or `pg_checksums_enhanced` makes it sound like it's much better than PG's version which I would like to avoid as well.

So really, I thought a bit about this some months back, but didn't come up with a good name back then either.

**Comment by mbanck** [comment]
> This is _doable_, but I will not replace a binary that comes with PostgreSQL.

Yeah, I would not expect (nor advise) you to replace a binary, hence my suggestions to just not ship it for v12, then no clash should occur?

**Comment by df7cb** [comment]
Upon rethinking the whole story, renaming to `pg_checksums_next` sounds like the best idea to me now.

**Comment by devrimgunduz** [comment]
+1 from me, too.

**Comment by devrimgunduz** [comment]
Any updates?

**Comment by devrimgunduz** [comment]
ping @mbanck @df7cb

**Comment by mbanck** [comment]
So, how about `pg_checksums_ext` (for external)?

**Comment by MichaelDBA** [comment]
we are still talkin bout this? funny

**Comment by mbanck** [comment]
#12 addresses this

**Comment by devrimgunduz-edb** [comment]
I need a "release" to package this.

**Comment by mbanck** [comment]
1.1 has been released
