### ISSUE TITLE
blocks skipped

### ISSUE THREAD

**Issue by gsmolk** [credativ/pg_checksums#8]
Hello, I'm getting output like:
`Blocks skipped: 12`

But even with `--verbose` flag I don`t get information about exact filenames and block numbers been skipped and, most importantly, the reasons for this:
https://pastebin.postgrespro.ru/?9746d0a33a1eb06f#t2VSFmVb1HKNFTm2/BwQxxZfeDyoEz39ucEa8iZbN4c=

It would be good to have WARNING about block been skipped and reason for this.

**Comment by mbanck** [comment]
First off, sorry for the late answer.

Which version of  `pg_checksums` was this?

If you are enabling checksums, the only way a block can be skipped is if it is new, i.e. recently created and without data or a checksum yet. This should be harmless.

Version of `pg_checksums` from 0.10 should also no longer report skipped blocks that way as they check fully zeroed out pages and no longer count those as skipped.

The reason those skipped blocks weren't report at `-v` level (but should have been at `-d`/debug level) is that in online mode a potentially very large number of them might be reported. Maybe we can change the behavior such that we log a warning if we're enabling checksums or are checking in offllne mode.

**Comment by mbanck** [comment]
I had another look at the code and I think skipped blocks should no longer happen when enabling checksums (as was the case here), or at least, there should be some additional output. So closing this issue.
